/** Auto-generated from Bank of America Adv SafeBalance statements ···8804 (joint). */
import type { FinanceTx } from "./financeStore";

export const BOFA_STATEMENT_TXS: FinanceTx[] = [
  {
    "id": "bofa-e80b6722cb2779be",
    "date": "2026-06-25",
    "kind": "expense",
    "amount": 11.2,
    "category": "Restaurants / coffee",
    "note": "SQ *QWENCH/DRNK",
    "merchant": "Qwench Drink Los Angeles CA",
    "source": "import",
    "externalId": "bofa-e80b6722cb2779be",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-b964b907624e7b67",
    "date": "2026-06-24",
    "kind": "expense",
    "amount": 885.76,
    "category": "Transfers",
    "note": "Zelle to ADRIANA GARCIA",
    "merchant": "Zelle to Adriana Garcia",
    "source": "import",
    "externalId": "bofa-b964b907624e7b67",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-10dae1e04964e3c2",
    "date": "2026-06-24",
    "kind": "expense",
    "amount": 4.0,
    "category": "Transfers",
    "note": "Zelle to ADRIANA GARCIA (small)",
    "merchant": "Zelle to Adriana Garcia",
    "source": "import",
    "externalId": "bofa-10dae1e04964e3c2",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-d15b97a6ef32b404",
    "date": "2026-06-22",
    "kind": "expense",
    "amount": 7.99,
    "category": "Subscriptions",
    "note": "PURCHASE ZUTOBI.COM",
    "merchant": "Zutobi.com",
    "source": "import",
    "externalId": "bofa-d15b97a6ef32b404",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-89895cf5fb9452db",
    "date": "2026-06-22",
    "kind": "expense",
    "amount": 3.24,
    "category": "Shopping",
    "note": "MOBILE PURCHASE Target T3217",
    "merchant": "Target Los Angeles CA",
    "source": "import",
    "externalId": "bofa-89895cf5fb9452db",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-0b9ece3892c619e2",
    "date": "2026-06-22",
    "kind": "expense",
    "amount": 46.93,
    "category": "Food / groceries",
    "note": "MOBILE PURCHASE Ralphs",
    "merchant": "Ralphs #0294 Los Angeles CA",
    "source": "import",
    "externalId": "bofa-0b9ece3892c619e2",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-5a586723d802643e",
    "date": "2026-06-22",
    "kind": "expense",
    "amount": 38.06,
    "category": "Build / tools",
    "note": "CHECKCARD GODADDY RECURRING",
    "merchant": "GoDaddy",
    "source": "import",
    "externalId": "bofa-5a586723d802643e",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-5423e43606774780",
    "date": "2026-06-16",
    "kind": "income",
    "amount": 1000.0,
    "category": "Transfers",
    "note": "Goldman Sachs Ba TRANSFER in",
    "merchant": "Goldman Sachs transfer",
    "source": "import",
    "externalId": "bofa-5423e43606774780",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-5b91872d76d106a1",
    "date": "2026-06-09",
    "kind": "expense",
    "amount": 7.99,
    "category": "Subscriptions",
    "note": "PURCHASE ZUTOBI.COM",
    "merchant": "Zutobi.com",
    "source": "import",
    "externalId": "bofa-5b91872d76d106a1",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-c9a6fe915607902b",
    "date": "2026-06-09",
    "kind": "expense",
    "amount": 17.0,
    "category": "Restaurants / coffee",
    "note": "SQ *QWENCH/DRNK",
    "merchant": "Qwench Drink Los Angeles CA",
    "source": "import",
    "externalId": "bofa-c9a6fe915607902b",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-06d5c40997ce4064",
    "date": "2026-06-08",
    "kind": "expense",
    "amount": 5.1,
    "category": "Restaurants / coffee",
    "note": "MOBILE PURCHASE Chipotle 4024",
    "merchant": "Chipotle 4024 Los Angeles CA",
    "source": "import",
    "externalId": "bofa-06d5c40997ce4064",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-f589eca77758ea99",
    "date": "2026-06-01",
    "kind": "expense",
    "amount": 700.0,
    "category": "Transfers",
    "note": "GOLDMAN SACHS BA TRANSFER out",
    "merchant": "Goldman Sachs transfer",
    "source": "import",
    "externalId": "bofa-f589eca77758ea99",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-d373856fe3aa06e4",
    "date": "2026-05-18",
    "kind": "income",
    "amount": 200.0,
    "category": "Income",
    "note": "Zelle from UMESH for \"Purchase\"",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "bofa-d373856fe3aa06e4",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-60db48c7674192d6",
    "date": "2026-05-18",
    "kind": "income",
    "amount": 300.0,
    "category": "Income",
    "note": "Zelle from BIMALA for \"daughter\"",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "bofa-60db48c7674192d6",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-cff3d713b59f3688",
    "date": "2026-05-18",
    "kind": "income",
    "amount": 1.0,
    "category": "Income",
    "note": "Zelle from BIMALA for \"daughter\"",
    "merchant": "Zelle from Bimala Shrestha",
    "source": "import",
    "externalId": "bofa-cff3d713b59f3688",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-6fa31d4bc086f135",
    "date": "2026-05-18",
    "kind": "expense",
    "amount": 400.0,
    "category": "Transfers",
    "note": "GOLDMAN SACHS BA TRANSFER out",
    "merchant": "Goldman Sachs transfer",
    "source": "import",
    "externalId": "bofa-6fa31d4bc086f135",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-03df887ce24396b6",
    "date": "2026-05-04",
    "kind": "income",
    "amount": 425.0,
    "category": "Income",
    "note": "Zelle from UMESH for \"Room rent\"",
    "merchant": "Zelle from Umesh Shrestha",
    "source": "import",
    "externalId": "bofa-03df887ce24396b6",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-93bff8b6a8636130",
    "date": "2026-05-04",
    "kind": "expense",
    "amount": 2000.0,
    "category": "Transfers",
    "note": "Online Banking transfer to SAV 7158",
    "merchant": "Transfer to BofA Savings \u00b7\u00b7\u00b77158",
    "source": "import",
    "externalId": "bofa-93bff8b6a8636130",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-1583bbbc4521c9c3",
    "date": "2026-05-01",
    "kind": "expense",
    "amount": 425.0,
    "category": "Transfers",
    "note": "Zelle to Ekene Nnamani for \"Leasing deposit\"",
    "merchant": "Zelle to Ekene Nnamani",
    "source": "import",
    "externalId": "bofa-1583bbbc4521c9c3",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-c5a1b2348c1d31b4",
    "date": "2026-04-02",
    "kind": "expense",
    "amount": 8000.0,
    "category": "Transfers",
    "note": "Online Banking transfer to SAV 7158",
    "merchant": "Transfer to BofA Savings \u00b7\u00b7\u00b77158",
    "source": "import",
    "externalId": "bofa-c5a1b2348c1d31b4",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-22ecd77d80e6ea85",
    "date": "2026-04-02",
    "kind": "expense",
    "amount": 241.96,
    "category": "Credit card payment",
    "note": "Mobile Banking payment to CRD 5499",
    "merchant": "Payment to BofA card \u00b7\u00b7\u00b75499",
    "source": "import",
    "externalId": "bofa-22ecd77d80e6ea85",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-c248d4d8d013dced",
    "date": "2026-04-01",
    "kind": "income",
    "amount": 9832.31,
    "category": "Transfers",
    "note": "Agent Assisted transfer from CD 3133",
    "merchant": "Transfer from BofA CD \u00b7\u00b7\u00b73133",
    "source": "import",
    "externalId": "bofa-c248d4d8d013dced",
    "pending": false,
    "accountId": "acc-bofa-checking",
  },
  {
    "id": "bofa-ef2cd03279264f25",
    "date": "2026-03-30",
    "kind": "expense",
    "amount": 7000.0,
    "category": "Transfers",
    "note": "Online Banking transfer to SAV 7158",
    "merchant": "Transfer to BofA Savings \u00b7\u00b7\u00b77158",
    "source": "import",
    "externalId": "bofa-ef2cd03279264f25",
    "pending": false,
    "accountId": "acc-bofa-checking",
  }
] as FinanceTx[];

export const BOFA_STATEMENT_ACCOUNTS = [
  { id: "acc-bofa-checking", name: "BofA Adv SafeBalance", kind: "checking" as const, balance: 5.14, institution: "Bank of America", mask: "8804" },
  { id: "acc-bofa-savings", name: "BofA Savings", kind: "savings" as const, balance: 0, institution: "Bank of America", mask: "7158" },
  { id: "acc-bofa-cd", name: "BofA CD", kind: "other" as const, balance: 0, institution: "Bank of America", mask: "3133" },
  { id: "acc-bofa-card", name: "BofA Card · 5499", kind: "credit" as const, balance: 0, institution: "Bank of America", mask: "5499", creditLimit: null },
];

export const BOFA_STATEMENT_META = { count: 23, from: "2026-03-30", to: "2026-06-26", source: "BofA Adv SafeBalance eStatements ···8804 (joint Melani + Bimala)", endingBalance: 5.14 };
